spring.application.name=server
spring.datasource.url=jdbc:h2:file:./matchme-db
spring.datasource.driver-class-name=org.h2.Driver
spring.jackson.serialization.write-bigdecimal-as-plain=true

logging.level.org.springframework.boot.autoconfigure.security=ERROR

spring.graphql.graphiql.enabled=false
spring.graphql.websocket.path=/graphql
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.oauth2.resource.servlet.OAuth2ResourceServerAutoConfiguration
server.port=${PORT:8080}

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:86400000}

spring.jpa.hibernate.ddl-auto=${DDL_AUTO}
spring.jpa.show-sql=${SHOW_SQL:false}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect



